import { act, renderHook } from '@testing-library/react';
import axios, { AxiosError, type AxiosResponse } from 'axios';
import { helpers } from '../../helpers/helpers';
import { ExternalAuthLoginLightspeedResponseType, ExternalAuthStatusLightspeedResponseType } from '../../types/types';
import { LightspeedAuthFlowState, useLightspeedAuthApi } from '../useAuthApi';

describe('useLightspeedAuthApi', () => {
  let spyPost;
  let spyGet;
  let spySetLightspeedUsername;
  let spyIsLightspeedAuthenticated;
  // Must be consistent with src/helpers/apiHelpers.ts `if (!data)` value
  const defaultApiHelperErrorMessage = 'Unknown error';
  const defaultVerificationUriComplete = 'https://sso.redhat.com/device?user_code=ABCD-EFGH';
  const defaultUsername = 'user';
  const defaultLoginResponse: AxiosResponse<ExternalAuthLoginLightspeedResponseType> = {
    status: 200,
    statusText: 'OK',
    headers: {},
    config: {} as any,
    data: {
      status: 'pending',
      user_code: 'ABCD-EFGH',
      verification_uri: 'https://sso.redhat.com/device',
      verification_uri_complete: defaultVerificationUriComplete
    }
  };
  const defaultStatusResponse: AxiosResponse<ExternalAuthStatusLightspeedResponseType> = {
    status: 200,
    statusText: 'OK',
    headers: {},
    config: {} as any,
    data: {
      status: 'valid',
      metadata: {
        status: 'valid',
        status_reason: '',
        account_number: '123456',
        org_id: '123456',
        username: defaultUsername,
        email: 'test@example.com',
        first_name: 'Jane',
        last_name: 'Doe'
      }
    }
  };

  beforeEach(() => {
    spyPost = jest.spyOn(axios, 'post');
    spyGet = jest.spyOn(axios, 'get');
    spySetLightspeedUsername = jest.spyOn(helpers, 'setLightspeedUsername');
    spyIsLightspeedAuthenticated = jest.spyOn(helpers, 'isLightspeedAuthenticated');
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  it('should request login and accept success', async () => {
    spyPost.mockResolvedValueOnce(defaultLoginResponse);
    spyGet.mockResolvedValueOnce(defaultStatusResponse);

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({ state: 'Initiated' });

    await act(async () => {
      await hook.result.current.requestLightspeedAuth();
    });

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({
      state: 'Successful'
    });
    expect(spyPost).toHaveBeenCalledTimes(1);
    expect(spyPost).toHaveBeenCalledWith(process.env.REACT_APP_AUTH_SERVICE_EXTERNAL_LOGIN);
    expect(spyGet).toHaveBeenCalledTimes(1);
  });

  it('should handle login request failure', async () => {
    const errorMessage = 'Network error';
    spyPost.mockRejectedValueOnce(new AxiosError(errorMessage, 'ERR_NETWORK', {} as any, {}));

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({ state: 'Initiated' });

    await act(async () => {
      await hook.result.current.requestLightspeedAuth();
    });

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({
      state: 'Errored',
      errorMessage: `${errorMessage}: ${defaultApiHelperErrorMessage}`
    });
    expect(spyPost).toHaveBeenCalledTimes(1);
    expect(spyGet).toHaveBeenCalledTimes(0);
  });

  it('should handle login request response without data', async () => {
    spyPost.mockResolvedValue({ data: undefined });

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({ state: 'Initiated' });

    await act(async () => {
      await hook.result.current.requestLightspeedAuth();
    });

    // error message is generated by axios, we don't want to assert the exact phrasing
    expect(hook.result.current.lightspeedAuthFlowState.state).toStrictEqual('Errored');
    expect(spyPost).toHaveBeenCalledTimes(1);
    expect(spyGet).toHaveBeenCalledTimes(0);
  });

  it('should handle status poll failure', async () => {
    const errorMessage = 'Network error';
    spyPost.mockResolvedValueOnce(defaultLoginResponse);
    spyGet.mockRejectedValueOnce(new AxiosError(errorMessage, 'ERR_NETWORK', {} as any, {}));

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({ state: 'Initiated' });

    await act(async () => {
      await hook.result.current.requestLightspeedAuth();
    });

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({
      state: 'Errored',
      errorMessage: `${errorMessage}: ${defaultApiHelperErrorMessage}`
    });
    expect(spyPost).toHaveBeenCalledTimes(1);
    expect(spyGet).toHaveBeenCalledTimes(1);
  });

  it('should handle status failure', async () => {
    spyPost.mockResolvedValueOnce(defaultLoginResponse);
    const errorMessage = 'Too many widgets';
    const response: AxiosResponse<ExternalAuthStatusLightspeedResponseType> = {
      ...defaultStatusResponse,
      data: {
        ...defaultStatusResponse.data,
        status: 'failed',
        metadata: {
          ...defaultStatusResponse.data.metadata,
          status: 'failed',
          status_reason: errorMessage
        }
      }
    };
    spyGet.mockResolvedValueOnce(response);

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({ state: 'Initiated' });

    await act(async () => {
      await hook.result.current.requestLightspeedAuth();
    });

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({
      state: 'Errored',
      errorMessage: errorMessage
    });
    expect(spyPost).toHaveBeenCalledTimes(1);
    expect(spyGet).toHaveBeenCalledTimes(1);
  });

  it('should handle status missing', async () => {
    spyPost.mockResolvedValueOnce(defaultLoginResponse);
    const errorMessage = 'Widget not created yet';
    const response: AxiosResponse<ExternalAuthStatusLightspeedResponseType> = {
      ...defaultStatusResponse,
      data: {
        ...defaultStatusResponse.data,
        status: 'missing',
        metadata: {
          ...defaultStatusResponse.data.metadata,
          status: 'missing',
          status_reason: errorMessage
        }
      }
    };
    spyGet.mockResolvedValueOnce(response);

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({ state: 'Initiated' });

    await act(async () => {
      await hook.result.current.requestLightspeedAuth();
    });

    expect(hook.result.current.lightspeedAuthFlowState).toEqual<LightspeedAuthFlowState>({
      state: 'Errored',
      errorMessage: expect.stringContaining('"context": "missing"')
    });
    expect(spyPost).toHaveBeenCalledTimes(1);
    expect(spyGet).toHaveBeenCalledTimes(1);
  });

  it('should handle status expired', async () => {
    spyPost.mockResolvedValueOnce(defaultLoginResponse);
    const errorMessage = 'Widget is too old';
    const response: AxiosResponse<ExternalAuthStatusLightspeedResponseType> = {
      ...defaultStatusResponse,
      data: {
        ...defaultStatusResponse.data,
        status: 'expired',
        metadata: {
          ...defaultStatusResponse.data.metadata,
          status: 'expired',
          status_reason: errorMessage
        }
      }
    };
    spyGet.mockResolvedValueOnce(response);

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({ state: 'Initiated' });

    await act(async () => {
      await hook.result.current.requestLightspeedAuth();
    });

    expect(hook.result.current.lightspeedAuthFlowState).toEqual<LightspeedAuthFlowState>({
      state: 'Errored',
      errorMessage: expect.stringContaining('"context": "expired"')
    });
    expect(spyPost).toHaveBeenCalledTimes(1);
    expect(spyGet).toHaveBeenCalledTimes(1);
  });

  it('should handle status poll response without data', async () => {
    spyPost.mockResolvedValueOnce(defaultLoginResponse);
    spyGet.mockResolvedValueOnce({ data: undefined });

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({ state: 'Initiated' });

    await act(async () => {
      await hook.result.current.requestLightspeedAuth();
    });

    // error message is "Unknown error", going through `t()`; a bit awkward to assert
    expect(hook.result.current.lightspeedAuthFlowState.state).toStrictEqual('Errored');
    expect(spyPost).toHaveBeenCalledTimes(1);
    expect(spyGet).toHaveBeenCalledTimes(1);
  });

  it('should poll a status endpoint', async () => {
    jest.useFakeTimers();
    spyPost.mockResolvedValueOnce(defaultLoginResponse);
    const pendingResponse: AxiosResponse<ExternalAuthStatusLightspeedResponseType> = {
      ...defaultStatusResponse,
      data: {
        ...defaultStatusResponse.data,
        status: 'pending',
        metadata: {
          ...defaultStatusResponse.data.metadata,
          status: 'pending'
        }
      }
    };
    spyGet.mockResolvedValueOnce(pendingResponse).mockResolvedValueOnce(defaultStatusResponse);

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({ state: 'Initiated' });

    await act(async () => {
      await hook.result.current.requestLightspeedAuth();
    });

    // useEffect(..., [lightspeedPollingTrigger, lightspeedAuthPollAttempt]) uses setTimeout,
    // which is scheduled to run AFTER above await completes. So we need another one.
    await act(async () => {
      await jest.advanceTimersToNextTimer();
    });

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({
      state: 'Successful'
    });
    expect(spyPost).toHaveBeenCalledTimes(1);
    expect(spyPost).toHaveBeenCalledWith(process.env.REACT_APP_AUTH_SERVICE_EXTERNAL_LOGIN);
    expect(spyGet).toHaveBeenCalledTimes(2);
    expect(spySetLightspeedUsername).toHaveBeenCalledTimes(1);
    expect(spySetLightspeedUsername).toHaveBeenCalledWith(defaultUsername);

    jest.useRealTimers();
  });

  it('should log out of Lightspeed', async () => {
    spyPost.mockResolvedValueOnce({});
    spyIsLightspeedAuthenticated.mockReturnValueOnce(true);

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedIsAuthenticated).toBe(true);

    await act(async () => {
      await hook.result.current.requestLightspeedAuthLogout();
    });
    expect(hook.result.current.lightspeedIsAuthenticated).toBe(false);
  });
});
