import { act, renderHook } from '@testing-library/react';
import axios from 'axios';
import { helpers } from '../../helpers/helpers';
import { ExternalAuthLoginLightspeedResponseType, ExternalAuthStatusLightspeedResponseType } from '../../types/types';
import { LightspeedAuthFlowState, useLightspeedAuthApi } from '../useAuthApi';

describe('useLightspeedAuthApi', () => {
  let spyPost;
  let spyGet;
  let spySetLightspeedUsername;
  // Must be consistent with src/helpers/apiHelpers.ts `if (!data)` value
  const defaultApiHelperErrorMessage = 'Unknown error';
  const defaultVerificationUriComplete = 'https://sso.redhat.com/device?user_code=ABCD-EFGH';
  const defaultUsername = 'user';
  const defaultLoginResponse: { data: ExternalAuthLoginLightspeedResponseType } = {
    data: {
      status: 'pending',
      user_code: 'ABCD-EFGH',
      verification_uri: 'https://sso.redhat.com/device',
      verification_uri_complete: defaultVerificationUriComplete
    }
  };
  const defaultStatusResponse: { data: ExternalAuthStatusLightspeedResponseType } = {
    data: {
      status: 'valid',
      metadata: {
        status: 'valid',
        status_reason: '',
        account_number: '123456',
        org_id: '123456',
        username: defaultUsername,
        email: 'test@example.com',
        first_name: 'Jane',
        last_name: 'Doe'
      }
    }
  };

  beforeEach(() => {
    spyPost = jest.spyOn(axios, 'post');
    spyGet = jest.spyOn(axios, 'get');
    spySetLightspeedUsername = jest.spyOn(helpers, 'setLightspeedUsername');
  });

  afterEach(() => {
    jest.restoreAllMocks();
  });

  it('should request login and accept success', async () => {
    spyPost.mockResolvedValueOnce(defaultLoginResponse);
    spyGet.mockResolvedValueOnce(defaultStatusResponse);

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({ state: 'Initiated' });

    await act(async () => {
      await hook.result.current.requestLightspeedAuth();
    });

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({
      state: 'Successful'
    });
    expect(spyPost).toHaveBeenCalledTimes(1);
    expect(spyPost).toHaveBeenCalledWith(
      process.env.REACT_APP_AUTH_SERVICE_EXTERNAL_LOGIN,
      {},
      { params: { auth_type: 'lightspeed' } }
    );
    expect(spyGet).toHaveBeenCalledTimes(1);
  });

  it('should handle login request failure', async () => {
    const errorMessage = 'Network error';
    spyPost.mockRejectedValue({ isAxiosError: true, message: errorMessage });

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({ state: 'Initiated' });

    await act(async () => {
      await hook.result.current.requestLightspeedAuth();
    });

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({
      state: 'Errored',
      errorMessage: `${errorMessage}: ${defaultApiHelperErrorMessage}`
    });
    expect(spyPost).toHaveBeenCalledTimes(1);
    expect(spyGet).toHaveBeenCalledTimes(0);
  });

  it('should handle login request response without data', async () => {
    spyPost.mockResolvedValue({ data: undefined });

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({ state: 'Initiated' });

    await act(async () => {
      await hook.result.current.requestLightspeedAuth();
    });

    // error message is generated by axios, we don't want to assert the exact phrasing
    expect(hook.result.current.lightspeedAuthFlowState.state).toStrictEqual('Errored');
    expect(spyPost).toHaveBeenCalledTimes(1);
    expect(spyGet).toHaveBeenCalledTimes(0);
  });

  it('should handle status poll failure', async () => {
    const errorMessage = 'Network error';
    spyPost.mockResolvedValueOnce(defaultLoginResponse);
    spyGet.mockRejectedValue({ isAxiosError: true, message: errorMessage });

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({ state: 'Initiated' });

    await act(async () => {
      await hook.result.current.requestLightspeedAuth();
    });

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({
      state: 'Errored',
      errorMessage: `${errorMessage}: ${defaultApiHelperErrorMessage}`
    });
    expect(spyPost).toHaveBeenCalledTimes(1);
    expect(spyGet).toHaveBeenCalledTimes(1);
  });

  it('should handle status failure', async () => {
    spyPost.mockResolvedValueOnce(defaultLoginResponse);
    const errorMessage = 'Too many widgets';
    spyGet.mockResolvedValueOnce({ data: { status: 'failed', metadata: { status_reason: errorMessage } } });

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({ state: 'Initiated' });

    await act(async () => {
      await hook.result.current.requestLightspeedAuth();
    });

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({
      state: 'Errored',
      errorMessage: errorMessage
    });
    expect(spyPost).toHaveBeenCalledTimes(1);
    expect(spyGet).toHaveBeenCalledTimes(1);
  });

  it('should handle status poll response without data', async () => {
    spyPost.mockResolvedValueOnce(defaultLoginResponse);
    spyGet.mockResolvedValueOnce({ data: undefined });

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({ state: 'Initiated' });

    await act(async () => {
      await hook.result.current.requestLightspeedAuth();
    });

    // error message is "Unknown error", going through `t()`; a bit awkward to assert
    expect(hook.result.current.lightspeedAuthFlowState.state).toStrictEqual('Errored');
    expect(spyPost).toHaveBeenCalledTimes(1);
    expect(spyGet).toHaveBeenCalledTimes(1);
  });

  it('should poll a status endpoint', async () => {
    jest.useFakeTimers();
    spyPost.mockResolvedValueOnce(defaultLoginResponse);
    spyGet.mockResolvedValueOnce({ data: { status: 'pending' } }).mockResolvedValueOnce(defaultStatusResponse);

    const hook = renderHook(() => useLightspeedAuthApi());

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({ state: 'Initiated' });

    await act(async () => {
      await hook.result.current.requestLightspeedAuth();
    });

    // useEffect(..., [mergeJobId, mergePollAttempt]) uses setTimeout, which is scheduled to run AFTER
    // above await completes. So we need another one.
    await act(async () => {
      await jest.advanceTimersToNextTimer();
    });

    expect(hook.result.current.lightspeedAuthFlowState).toStrictEqual<LightspeedAuthFlowState>({
      state: 'Successful'
    });
    expect(spyPost).toHaveBeenCalledTimes(1);
    expect(spyPost).toHaveBeenCalledWith(
      process.env.REACT_APP_AUTH_SERVICE_EXTERNAL_LOGIN,
      {},
      { params: { auth_type: 'lightspeed' } }
    );
    expect(spyGet).toHaveBeenCalledTimes(2);
    expect(spySetLightspeedUsername).toHaveBeenCalledTimes(1);
    expect(spySetLightspeedUsername).toHaveBeenCalledWith(defaultUsername);

    jest.useRealTimers();
  });
});
