const CONFIRMATION_MODAL_SHOW = 'CONFIRMATION_MODAL_SHOW';
const CONFIRMATION_MODAL_HIDE = 'CONFIRMATION_MODAL_HIDE';

const confirmationModalTypes = {
  CONFIRMATION_MODAL_SHOW,
  CONFIRMATION_MODAL_HIDE
};

export { confirmationModalTypes as default, confirmationModalTypes, CONFIRMATION_MODAL_SHOW, CONFIRMATION_MODAL_HIDE };
