const ADD_CREDENTIAL = 'ADD_CREDENTIAL';
const DELETE_CREDENTIAL = 'DELETE_CREDENTIAL';
const DELETE_CREDENTIALS = 'DELETE_CREDENTIALS';
const GET_CREDENTIAL = 'GET_CREDENTIAL';
const GET_CREDENTIALS = 'GET_CREDENTIALS';
const GET_WIZARD_CREDENTIALS = 'GET_WIZARD_CREDENTIALS';
const UPDATE_CREDENTIAL = 'UPDATE_CREDENTIAL';
const CREATE_CREDENTIAL_SHOW = 'CREATE_CREDENTIAL_SHOW';
const EDIT_CREDENTIAL_SHOW = 'EDIT_CREDENTIAL_SHOW';
const UPDATE_CREDENTIAL_HIDE = 'UPDATE_CREDENTIAL_HIDE';
const RESET_CREDENTIAL_UPDATE_STATUS = 'RESET_CREDENTIAL_UPDATE_STATUS';

const SELECT_CREDENTIAL = 'SELECT_CREDENTIAL';
const DESELECT_CREDENTIAL = 'DESELECT_CREDENTIAL';
const EXPANDED_CREDENTIAL = 'EXPANDED_CREDENTIAL';
const NOT_EXPANDED_CREDENTIAL = 'NOT_EXPANDED_CREDENTIAL';
const UPDATE_CREDENTIALS = 'UPDATE_CREDENTIALS';
const CONFIRM_DELETE_CREDENTIAL = 'CONFIRM_DELETE_CREDENTIAL';
const RESET_DELETE_CREDENTIAL = 'RESET_DELETE_CREDENTIAL';

const credentialsTypes = {
  ADD_CREDENTIAL,
  UPDATE_CREDENTIAL,
  DELETE_CREDENTIAL,
  DELETE_CREDENTIALS,
  GET_CREDENTIAL,
  GET_CREDENTIALS,
  GET_WIZARD_CREDENTIALS,
  CREATE_CREDENTIAL_SHOW,
  EDIT_CREDENTIAL_SHOW,
  UPDATE_CREDENTIAL_HIDE,
  RESET_CREDENTIAL_UPDATE_STATUS,
  SELECT_CREDENTIAL,
  DESELECT_CREDENTIAL,
  EXPANDED_CREDENTIAL,
  NOT_EXPANDED_CREDENTIAL,
  UPDATE_CREDENTIALS,
  CONFIRM_DELETE_CREDENTIAL,
  RESET_DELETE_CREDENTIAL
};

export {
  credentialsTypes as default,
  credentialsTypes,
  ADD_CREDENTIAL,
  UPDATE_CREDENTIAL,
  DELETE_CREDENTIAL,
  DELETE_CREDENTIALS,
  GET_CREDENTIAL,
  GET_CREDENTIALS,
  GET_WIZARD_CREDENTIALS,
  CREATE_CREDENTIAL_SHOW,
  EDIT_CREDENTIAL_SHOW,
  UPDATE_CREDENTIAL_HIDE,
  RESET_CREDENTIAL_UPDATE_STATUS,
  SELECT_CREDENTIAL,
  DESELECT_CREDENTIAL,
  EXPANDED_CREDENTIAL,
  NOT_EXPANDED_CREDENTIAL,
  UPDATE_CREDENTIALS,
  CONFIRM_DELETE_CREDENTIAL,
  RESET_DELETE_CREDENTIAL
};
