const ADD_CREDENTIAL = 'ADD_CREDENTIAL';
const DELETE_CREDENTIAL = 'DELETE_CREDENTIAL';
const GET_CREDENTIALS = 'GET_CREDENTIALS';
const UPDATE_CREDENTIAL = 'UPDATE_CREDENTIAL';
const CREATE_CREDENTIAL_SHOW = 'CREATE_CREDENTIAL_SHOW';
const EDIT_CREDENTIAL_SHOW = 'EDIT_CREDENTIAL_SHOW';
const UPDATE_CREDENTIAL_HIDE = 'UPDATE_CREDENTIAL_HIDE';

const SELECT_CREDENTIAL = 'SELECT_CREDENTIAL';
const DESELECT_CREDENTIAL = 'DESELECT_CREDENTIAL';
const EXPANDED_CREDENTIAL = 'EXPANDED_CREDENTIAL';
const NOT_EXPANDED_CREDENTIAL = 'NOT_EXPANDED_CREDENTIAL';
const UPDATE_CREDENTIALS = 'UPDATE_CREDENTIALS';

const credentialsTypes = {
  ADD_CREDENTIAL,
  UPDATE_CREDENTIAL,
  DELETE_CREDENTIAL,
  GET_CREDENTIALS,
  CREATE_CREDENTIAL_SHOW,
  EDIT_CREDENTIAL_SHOW,
  UPDATE_CREDENTIAL_HIDE,
  SELECT_CREDENTIAL,
  DESELECT_CREDENTIAL,
  EXPANDED_CREDENTIAL,
  NOT_EXPANDED_CREDENTIAL,
  UPDATE_CREDENTIALS
};

export {
  credentialsTypes as default,
  credentialsTypes,
  ADD_CREDENTIAL,
  UPDATE_CREDENTIAL,
  DELETE_CREDENTIAL,
  GET_CREDENTIALS,
  CREATE_CREDENTIAL_SHOW,
  EDIT_CREDENTIAL_SHOW,
  UPDATE_CREDENTIAL_HIDE,
  SELECT_CREDENTIAL,
  DESELECT_CREDENTIAL,
  EXPANDED_CREDENTIAL,
  NOT_EXPANDED_CREDENTIAL,
  UPDATE_CREDENTIALS
};
