const ADD_SCAN = 'ADD_SCAN';
const ADD_START_SCAN = 'ADD_START_SCAN';
const UPDATE_SCANS = 'UPDATE_SCANS';
const DELETE_SCAN = 'DELETE_SCAN';

const GET_SCANS = 'GET_SCANS';
const GET_SCAN_CONNECTION_RESULTS = 'GET_SCAN_CONNECTION_RESULTS';
const GET_SCAN_INSPECTION_RESULTS = 'GET_SCAN_INSPECTION_RESULTS';
const GET_SCAN_JOB = 'GET_SCAN_JOB';
const GET_SCAN_JOBS = 'GET_SCAN_JOBS';

const START_SCAN = 'START_SCAN';
const CANCEL_SCAN = 'CANCEL_SCAN';
const PAUSE_SCAN = 'PAUSE_SCAN';
const RESTART_SCAN = 'RESTART_SCAN';

const EDIT_SCAN_HIDE = 'EDIT_SCAN_HIDE';
const EDIT_SCAN_SHOW = 'EDIT_SCAN_SHOW';
const MERGE_SCAN_DIALOG_HIDE = 'MERGE_SCAN_DIALOG_HIDE';
const MERGE_SCAN_DIALOG_SHOW = 'MERGE_SCAN_DIALOG_SHOW';

const SELECT_SCAN = 'SELECT_SCAN';
const DESELECT_SCAN = 'DESELECT_SCAN';
const EXPANDED_SCAN = 'EXPANDED_SCAN';
const NOT_EXPANDED_SCAN = 'NOT_EXPANDED_SCAN';

const RESET_ACTIONS = 'RESET_SCAN_ACTIONS';

const scansTypes = {
  ADD_SCAN,
  ADD_START_SCAN,
  UPDATE_SCANS,
  DELETE_SCAN,
  GET_SCANS,
  GET_SCAN_CONNECTION_RESULTS,
  GET_SCAN_INSPECTION_RESULTS,
  GET_SCAN_JOB,
  GET_SCAN_JOBS,
  START_SCAN,
  CANCEL_SCAN,
  PAUSE_SCAN,
  RESTART_SCAN,
  EDIT_SCAN_HIDE,
  EDIT_SCAN_SHOW,
  MERGE_SCAN_DIALOG_HIDE,
  MERGE_SCAN_DIALOG_SHOW,
  SELECT_SCAN,
  DESELECT_SCAN,
  EXPANDED_SCAN,
  NOT_EXPANDED_SCAN,
  RESET_ACTIONS
};

export {
  scansTypes as default,
  scansTypes,
  ADD_SCAN,
  ADD_START_SCAN,
  UPDATE_SCANS,
  DELETE_SCAN,
  GET_SCANS,
  GET_SCAN_CONNECTION_RESULTS,
  GET_SCAN_INSPECTION_RESULTS,
  GET_SCAN_JOB,
  GET_SCAN_JOBS,
  START_SCAN,
  CANCEL_SCAN,
  PAUSE_SCAN,
  RESTART_SCAN,
  EDIT_SCAN_HIDE,
  EDIT_SCAN_SHOW,
  MERGE_SCAN_DIALOG_HIDE,
  MERGE_SCAN_DIALOG_SHOW,
  SELECT_SCAN,
  DESELECT_SCAN,
  EXPANDED_SCAN,
  NOT_EXPANDED_SCAN,
  RESET_ACTIONS
};
