const ADD_SOURCE = 'ADD_SOURCE';
const CONFIRM_DELETE_SOURCE = 'CONFIRM_DELETE_SOURCE';
const DELETE_SOURCE = 'DELETE_SOURCE';
const DELETE_SOURCES = 'DELETE_SOURCES';
const GET_SCANS_SOURCES = 'GET_SCANS_SOURCES';
const GET_SOURCE = 'GET_SOURCE';
const GET_SOURCES = 'GET_SOURCES';
const UPDATE_SOURCES = 'UPDATE_SOURCES';
const UPDATE_SOURCE = 'UPDATE_SOURCE';
const UPDATE_SOURCE_WIZARD = 'UPDATE_SOURCE_WIZARD';
const VALID_SOURCE_WIZARD_STEPONE = 'VALID_SOURCE_WIZARD_STEPONE';
const VALID_SOURCE_WIZARD_STEPTWO = 'VALID_SOURCE_WIZARD_STEPTWO';
const INVALID_SOURCE_WIZARD_STEPTWO = 'INVALID_SOURCE_WIZARD_STEPTWO';
const CREATE_SOURCE_SHOW = 'CREATE_SOURCE_SHOW';
const EDIT_SOURCE_SHOW = 'EDIT_SOURCE_SHOW';
const UPDATE_SOURCE_HIDE = 'UPDATE_SOURCE_HIDE';
const SELECT_SOURCE = 'SELECT_SOURCE';
const DESELECT_SOURCE = 'DESELECT_SOURCE';
const EXPANDED_SOURCE = 'EXPANDED_SOURCE';
const NOT_EXPANDED_SOURCE = 'NOT_EXPANDED_SOURCE';
const RESET_DELETE_SOURCE = 'RESET_DELETE_SOURCE';

const sourcesTypes = {
  ADD_SOURCE,
  CONFIRM_DELETE_SOURCE,
  DELETE_SOURCE,
  DELETE_SOURCES,
  GET_SCANS_SOURCES,
  GET_SOURCE,
  GET_SOURCES,
  UPDATE_SOURCES,
  UPDATE_SOURCE,
  UPDATE_SOURCE_WIZARD,
  VALID_SOURCE_WIZARD_STEPONE,
  VALID_SOURCE_WIZARD_STEPTWO,
  INVALID_SOURCE_WIZARD_STEPTWO,
  CREATE_SOURCE_SHOW,
  EDIT_SOURCE_SHOW,
  UPDATE_SOURCE_HIDE,
  SELECT_SOURCE,
  DESELECT_SOURCE,
  EXPANDED_SOURCE,
  NOT_EXPANDED_SOURCE,
  RESET_DELETE_SOURCE
};

export {
  sourcesTypes as default,
  sourcesTypes,
  ADD_SOURCE,
  CONFIRM_DELETE_SOURCE,
  DELETE_SOURCE,
  DELETE_SOURCES,
  GET_SCANS_SOURCES,
  GET_SOURCE,
  GET_SOURCES,
  UPDATE_SOURCES,
  UPDATE_SOURCE,
  UPDATE_SOURCE_WIZARD,
  VALID_SOURCE_WIZARD_STEPONE,
  VALID_SOURCE_WIZARD_STEPTWO,
  INVALID_SOURCE_WIZARD_STEPTWO,
  CREATE_SOURCE_SHOW,
  EDIT_SOURCE_SHOW,
  UPDATE_SOURCE_HIDE,
  SELECT_SOURCE,
  DESELECT_SOURCE,
  EXPANDED_SOURCE,
  NOT_EXPANDED_SOURCE,
  RESET_DELETE_SOURCE
};
