const SOURCES_VIEW = 'SOURCES_VIEW';
const SCANS_VIEW = 'SCANS_VIEW';
const CREDENTIALS_VIEW = 'CREDENTIALS_VIEW';

const RESET_PAGE = 'RESET_PAGE';
const SET_FILTER = 'SET_FILTER';
const SET_QUERY = 'SET_QUERY';
const UPDATE_VIEW = 'UPDATE_VIEW';

const viewTypes = {
  SOURCES_VIEW,
  SCANS_VIEW,
  CREDENTIALS_VIEW,
  RESET_PAGE,
  SET_FILTER,
  SET_QUERY,
  UPDATE_VIEW
};

export {
  viewTypes as default,
  viewTypes,
  SOURCES_VIEW,
  SCANS_VIEW,
  CREDENTIALS_VIEW,
  RESET_PAGE,
  SET_FILTER,
  SET_QUERY,
  UPDATE_VIEW
};
