const SOURCES_VIEW = 'SOURCES_VIEW';
const SCANS_VIEW = 'SCANS_VIEW';
const CREDENTIALS_VIEW = 'CREDENTIALS_VIEW';

const viewTypes = {
  SOURCES_VIEW,
  SCANS_VIEW,
  CREDENTIALS_VIEW
};

export { viewTypes as default, viewTypes, SOURCES_VIEW, SCANS_VIEW, CREDENTIALS_VIEW };
